# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.4"

[buildpack]
id       = "paketo-buildpacks/bellsoft-liberica"
name     = "Paketo BellSoft Liberica Buildpack"
version  = "{{.version}}"
homepage = "https://github.com/paketo-buildpacks/bellsoft-liberica"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[metadata.configurations]]
name        = "BPL_JVM_HEAD_ROOM"
description = "the headroom in memory calculation"
default     = "0"
launch      = true

[[metadata.configurations]]
name        = "BPL_JVM_LOADED_CLASS_COUNT"
description = "the number of loaded classes in memory calculation"
default     = "35% of classes"
launch      = true

[[metadata.configurations]]
name        = "BPL_JVM_THREAD_COUNT"
description = "the number of threads in memory calculation"
default     = "250"
launch      = true

[[metadata.configurations]]
name        = "BP_JVM_VERSION"
description = "the Java version"
default     = "11.*"
build       = true

[[metadata.configurations]]
name        = "JAVA_TOOL_OPTIONS"
description = "the JVM launch flags"
launch      = true

[[metadata.dependencies]]
id      = "jdk"
name    = "BellSoft Liberica JDK"
version = "8.0.265"
uri     = "https://github.com/bell-sw/Liberica/releases/download/8u265+1/bellsoft-jdk8u265+1-linux-amd64.tar.gz"
sha256  = "e060f41eb364b69d2a088de573c55e6d1b11eee62037c12ba522375c16a87b57"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jre"
name    = "BellSoft Liberica JRE"
version = "8.0.265"
uri     = "https://github.com/bell-sw/Liberica/releases/download/8u265+1/bellsoft-jre8u265+1-linux-amd64.tar.gz"
sha256  = "a754ed4e922630d18ec382e810460009a176e1cb9d2955b200e2dca972f6702e"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jdk"
name    = "BellSoft Liberica JDK"
version = "11.0.0"
uri     = "placeholder"
sha256  = "placeholder"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jre"
name    = "BellSoft Liberica JRE"
version = "11.0.0"
uri     = "placeholder"
sha256  = "placeholder"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jdk"
name    = "BellSoft Liberica JDK"
version = "14.0.0"
uri     = "placeholder"
sha256  = "placeholder"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jre"
name    = "BellSoft Liberica JRE"
version = "14.0.0"
uri     = "placeholder"
sha256  = "placeholder"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jdk"
name    = "BellSoft Liberica JDK"
version = "15.0.0"
uri     = "placeholder"
sha256  = "placeholder"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jre"
name    = "BellSoft Liberica JRE"
version = "15.0.0"
uri     = "https://github.com/bell-sw/Liberica/releases/download/15+36/bellsoft-jre15+36-linux-amd64.tar.gz"
sha256  = "39e34aad64563be005dd7495104795d6640febee5ab052fc0f80a6b1943d2d28"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jvmkill"
name    = "JVMKill Agent"
version = "0.0.0"
uri     = "placeholder"
sha256  = "placeholder"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jvmkill/blob/main/LICENSE"

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "bin/helper",
  "bin/main",
  "buildpack.toml",
]
